version: '3.1'
services:
  stats-client:
    build: stats-service/stats-service-client
    image: stats-service-client
    container_name: ewm-stats-client
    hostname: stats-client
    ports:
      - "9090:9090"
    depends_on:
      - stats-server

  stats-server:
    build: stats-service/stats-service-server
    image: stats-service-server
    container_name: ewm-stats-server
    hostname: stats-server
    ports:
      - "8081:8081"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    hostname: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

